package genesismesh

import (
	"encoding/json"
	"errors"
	"os"
	"reflect"
	"testing"
	"time"
)

// Shared conformance suite "canonical" (v1.2.0), generated by the Python
// reference (genesismesh/conformance/generate_vectors.py canonical) and copied
// unchanged: input every implementation reads alike or refuses by reason, and
// the canonical form of records.

type canonicalVector struct {
	ID       string                     `json:"id"`
	Kind     string                     `json:"kind"`
	Input    json.RawMessage            `json:"input"`
	Expected map[string]json.RawMessage `json:"expected"`
}

func loadCanonicalSuite(t *testing.T) []canonicalVector {
	t.Helper()
	raw, err := os.ReadFile("testdata/conformance/canonical.json")
	if err != nil {
		t.Fatal(err)
	}
	var suite struct {
		Vectors []canonicalVector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &suite); err != nil {
		t.Fatal(err)
	}
	return suite.Vectors
}

func expectJSON(t *testing.T, id string, got interface{}, want map[string]json.RawMessage) {
	t.Helper()
	gotRaw, _ := json.Marshal(got)
	wantRaw, _ := json.Marshal(want)
	var g, w interface{}
	_ = json.Unmarshal(gotRaw, &g)
	_ = json.Unmarshal(wantRaw, &w)
	if !reflect.DeepEqual(g, w) {
		t.Errorf("%s: got %s, want %s", id, gotRaw, wantRaw)
	}
}

func TestConformanceCanonicalVectors(t *testing.T) {
	vectors := loadCanonicalSuite(t)
	if len(vectors) < 70 {
		t.Fatalf("only %d vectors", len(vectors))
	}
	for _, v := range vectors {
		var input map[string]json.RawMessage
		_ = json.Unmarshal(v.Input, &input)
		switch v.Kind {
		case "json":
			var text string
			if err := json.Unmarshal(v.Input, &text); err != nil {
				t.Fatal(err)
			}
			canonical, err := CanonicalJSON([]byte(text))
			var refused *StrictJSONError
			switch {
			case err == nil:
				expectJSON(t, v.ID, map[string]string{"canonical": canonical}, v.Expected)
			case errors.As(err, &refused):
				expectJSON(t, v.ID, map[string]string{"refused": refused.Reason}, v.Expected)
			default:
				t.Errorf("%s: %v", v.ID, err)
			}
		case "timestamp":
			var value string
			_ = json.Unmarshal(v.Input, &value)
			expectJSON(t, v.ID, map[string]bool{"canonical": CanonicalTimestamp(value)}, v.Expected)
		case "verify_decision":
			now, err := time.Parse(time.RFC3339Nano, text(t, input["now"]))
			if err != nil {
				t.Fatal(err)
			}
			got, err := VerifyBoundaryDecision(input["decision"], DecisionVerifyOptions{
				OperatorPublicKeys: strings_(t, input["operator_public_keys"]), Now: now,
			})
			if err != nil {
				t.Fatalf("%s: %v", v.ID, err)
			}
			expectJSON(t, v.ID, map[string]interface{}{"accepted": got.Accepted, "reason": got.Reason}, v.Expected)
		case "verify_agreement":
			got, err := VerifyAgreement(input["agreement"],
				strings_(t, input["offerer_public_keys"]), strings_(t, input["responder_public_keys"]), "")
			if err != nil {
				t.Fatalf("%s: %v", v.ID, err)
			}
			expectJSON(t, v.ID, map[string]interface{}{"accepted": got.Accepted, "reason": got.Reason}, v.Expected)
		case "verify_intent":
			at, err := ParseTimestamp(text(t, input["at"]))
			if err != nil {
				t.Fatal(err)
			}
			got, err := VerifyDataAccessIntent(input["intent"], input["policy"], strings_(t, input["agent_public_keys"]), at)
			if err != nil {
				t.Fatalf("%s: %v", v.ID, err)
			}
			detail := ""
			if len(got.Violations) > 0 {
				detail = got.Violations[0].Detail
			}
			expectJSON(t, v.ID, map[string]string{"detail": detail}, v.Expected)
		default:
			t.Errorf("%s: unknown kind %s", v.ID, v.Kind)
		}
	}
}

func TestCanonicalTimestampPathsAtAnyDepth(t *testing.T) {
	for _, v := range loadCanonicalSuite(t) {
		if v.ID != "verify-agreement-signed-non-canonical-timestamp" {
			continue
		}
		var input map[string]json.RawMessage
		_ = json.Unmarshal(v.Input, &input)
		agreement, err := decodeObject(input["agreement"], "agreement")
		if err != nil {
			t.Fatal(err)
		}
		if got := nonCanonicalTimestamps("AgreementRecord", agreement); !reflect.DeepEqual(got, []string{"agreed_terms.valid_from"}) {
			t.Fatalf("got %v", got)
		}
		return
	}
	t.Fatal("vector missing")
}

func TestStrictJSONUnderflowIsZero(t *testing.T) {
	got, err := CanonicalJSON([]byte(`[1e-400]`))
	if err != nil || got != "[0.0]" {
		t.Fatalf("got %q %v", got, err)
	}
}
