package genesismesh

import (
	"encoding/json"
	"errors"
	"os"
	"reflect"
	"sort"
	"testing"
	"time"
)

// Shared conformance suite "field_registry" (v1.2.0), generated by the Python
// reference (genesismesh/conformance/generate_vectors.py field_registry) and
// copied unchanged: the field registry of signed records and the fields every
// verifier refuses.

type fieldRegistryVector struct {
	ID        string                     `json:"id"`
	Kind      string                     `json:"kind"`
	Model     string                     `json:"model"`
	Record    json.RawMessage            `json:"record"`
	EntryKind string                     `json:"entry_kind"`
	Input     map[string]json.RawMessage `json:"input"`
	Expected  struct {
		UnknownFields []string `json:"unknown_fields"`
		Known         *bool    `json:"known"`
		Accepted      *bool    `json:"accepted"`
		Reason        string   `json:"reason"`
	} `json:"expected"`
}

func loadFieldRegistrySuite(t *testing.T) (json.RawMessage, []fieldRegistryVector) {
	t.Helper()
	raw, err := os.ReadFile("testdata/conformance/field_registry.json")
	if err != nil {
		t.Fatal(err)
	}
	var suite struct {
		Registry json.RawMessage       `json:"registry"`
		Vectors  []fieldRegistryVector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &suite); err != nil {
		t.Fatal(err)
	}
	return suite.Registry, suite.Vectors
}

func TestConformanceFieldRegistryIsEmbedded(t *testing.T) {
	registry, _ := loadFieldRegistrySuite(t)
	var want, got interface{}
	if err := json.Unmarshal(registry, &want); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(canonicalRegistryJSON, &got); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(want, got) {
		t.Fatal("canonical_registry.json differs from the suite: run `python scripts/sync_canonical_registry.py`")
	}
}

func TestCanonicalRulesEqualTheRegistrys(t *testing.T) {
	if got := canonicalRegistry.Models["BoundaryDecision"].OmitWhenNone; !reflect.DeepEqual(decisionOmittedWhenAbsent, got) {
		t.Errorf("decisionOmittedWhenAbsent %v, registry %v", decisionOmittedWhenAbsent, got)
	}
	if got := canonicalRegistry.Models["AgreementRecord"].CanonicalFields; !reflect.DeepEqual(agreementCanonicalFields, got) {
		t.Errorf("agreementCanonicalFields %v, registry %v", agreementCanonicalFields, got)
	}
}

func TestConformanceFieldRegistryVectors(t *testing.T) {
	_, vectors := loadFieldRegistrySuite(t)
	if len(vectors) < 70 {
		t.Fatalf("only %d vectors", len(vectors))
	}
	for _, v := range vectors {
		switch v.Kind {
		case "unknown_fields":
			got, err := UnknownFields(v.Model, v.Record)
			if err != nil {
				t.Fatalf("%s: %v", v.ID, err)
			}
			want := append([]string(nil), v.Expected.UnknownFields...)
			sort.Strings(want)
			if len(got) != len(want) || (len(got) > 0 && !reflect.DeepEqual(got, want)) {
				t.Errorf("%s: got %v, want %v", v.ID, got, want)
			}
		case "verify_decision":
			now, err := time.Parse(time.RFC3339Nano, text(t, v.Input["now"]))
			if err != nil {
				t.Fatal(err)
			}
			got, err := VerifyBoundaryDecision(v.Input["decision"], DecisionVerifyOptions{
				OperatorPublicKeys: strings_(t, v.Input["operator_public_keys"]), Now: now,
			})
			if err != nil || got.Accepted != *v.Expected.Accepted || got.Reason != v.Expected.Reason {
				t.Errorf("%s: got %+v %v, want %v %s", v.ID, got, err, *v.Expected.Accepted, v.Expected.Reason)
			}
		case "verify_agreement":
			got, err := VerifyAgreement(v.Input["agreement"],
				strings_(t, v.Input["offerer_public_keys"]), strings_(t, v.Input["responder_public_keys"]), "")
			if err != nil || got.Accepted != *v.Expected.Accepted || got.Reason != v.Expected.Reason {
				t.Errorf("%s: got %+v %v, want %v %s", v.ID, got, err, *v.Expected.Accepted, v.Expected.Reason)
			}
		case "entry_kind", "export":
			// This package has no evidence export verifier.
		default:
			t.Errorf("%s: unknown kind %s", v.ID, v.Kind)
		}
	}
}

func withField(t *testing.T, raw json.RawMessage, key string) []byte {
	t.Helper()
	obj, err := decodeObject(raw, "record")
	if err != nil {
		t.Fatal(err)
	}
	obj[key] = "x"
	out, err := json.Marshal(obj)
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func registryVector(t *testing.T, id string) fieldRegistryVector {
	t.Helper()
	_, vectors := loadFieldRegistrySuite(t)
	for _, v := range vectors {
		if v.ID == id {
			return v
		}
	}
	t.Fatalf("no vector %s", id)
	return fieldRegistryVector{}
}

func TestAnExpectedPolicyWithAnUnknownFieldIsRefusedByName(t *testing.T) {
	newer := registryVector(t, "verify-decision-newer-signed-field").Input
	now, err := time.Parse(time.RFC3339Nano, text(t, newer["now"]))
	if err != nil {
		t.Fatal(err)
	}
	policy := registryVector(t, "boundarypolicy-top").Record
	got, err := VerifyBoundaryDecision(newer["decision"], DecisionVerifyOptions{
		OperatorPublicKeys: strings_(t, newer["operator_public_keys"]), Now: now,
		ExpectedPolicies: [][]byte{policy},
	})
	if err != nil || got.Reason != "unknown_field" {
		t.Fatalf("got %+v %v", got, err)
	}
}

func TestAFieldOutsideTheSignatureFailsTheSignature(t *testing.T) {
	vectors := loadVectors(t)
	byID := map[string]vector{}
	for _, v := range vectors {
		byID[v.ID] = v
	}

	bd := byID["bd-003"]
	now, err := ParseTimestamp(text(t, bd.Input["now"]))
	if err != nil {
		t.Fatal(err)
	}
	opts := DecisionVerifyOptions{OperatorPublicKeys: strings_(t, bd.Input["operator_public_keys"]), Now: now}
	ok, err := VerifyBoundaryDecision(bd.Input["decision"], opts)
	if err != nil || ok.Reason != "authorized" {
		t.Fatalf("baseline: %+v %v", ok, err)
	}
	added, err := VerifyBoundaryDecision(withField(t, bd.Input["decision"], "risk_tier"), opts)
	if err != nil || added.Accepted || added.Reason != "invalid_signature" {
		t.Fatalf("decision with an unsigned field: %+v %v", added, err)
	}

	agr := byID["agr-001"]
	res, err := VerifyAgreement(withField(t, agr.Input["agreement"], "x"),
		strings_(t, agr.Input["offerer_public_keys"]), strings_(t, agr.Input["responder_public_keys"]), "")
	if err != nil || !res.Accepted {
		t.Fatalf("an agreement's unsigned fields are not checked: %+v %v", res, err)
	}

	pol := byID["pol-001"]
	valid, err := VerifyDataLicensePolicySignature(withField(t, pol.Input["policy"], "x"), strings_(t, pol.Input["licensor_public_keys"]))
	if err != nil || valid {
		t.Fatalf("policy with an unknown field verified: %v %v", valid, err)
	}

	in := byID["int-001"]
	at, _ := ParseTimestamp(text(t, in.Input["at"]))
	intent, err := VerifyDataAccessIntent(withField(t, in.Input["intent"], "x"), in.Input["policy"],
		strings_(t, in.Input["agent_public_keys"]), at)
	if err != nil || intent.Valid || len(intent.Violations) != 1 || intent.Violations[0].Detail != "Invalid intent signature" {
		t.Fatalf("intent with an unsigned field: %+v %v", intent, err)
	}
	policy, err := VerifyDataAccessIntent(in.Input["intent"], withField(t, in.Input["policy"], "x"),
		strings_(t, in.Input["agent_public_keys"]), at)
	if err != nil || policy.Valid || len(policy.Violations) != 1 || policy.Violations[0].Detail != "Unknown field: policy.x" {
		t.Fatalf("intent against a policy with an unknown field: %+v %v", policy, err)
	}
}

func TestAnEmptyKeyIsAnUnknownField(t *testing.T) {
	// v1.3.0: a model without a signature field does not read "" as one.
	found, err := UnknownFields("ContextRecord", []byte(`{"":1,"zz":2}`))
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(found, []string{"", "zz"}) {
		t.Fatalf("got %v", found)
	}
}

func TestTextThatIsNotUTF8IsRefusedFirst(t *testing.T) {
	// v1.3.0: as every implementation that decodes the text first.
	err := CheckStrictJSON([]byte("[-0,\"\xff\"]"))
	var strict *StrictJSONError
	if !errors.As(err, &strict) || strict.Reason != "invalid_json" {
		t.Fatalf("got %v", err)
	}
}
