package genesismesh

import (
	"encoding/json"
	"os"
	"reflect"
	"sort"
	"testing"
)

// Shared conformance suite "canonical" (v1.2.0), generated by the Python
// reference (genesismesh/conformance/generate_vectors.py canonical) and
// copied unchanged: the field registry of signed records and the fields
// every verifier refuses.

type canonicalVector struct {
	ID        string          `json:"id"`
	Kind      string          `json:"kind"`
	Model     string          `json:"model"`
	Record    json.RawMessage `json:"record"`
	EntryKind string          `json:"entry_kind"`
	Expected  struct {
		UnknownFields []string `json:"unknown_fields"`
		Known         *bool    `json:"known"`
	} `json:"expected"`
}

func loadCanonicalSuite(t *testing.T) (json.RawMessage, []canonicalVector) {
	t.Helper()
	raw, err := os.ReadFile("testdata/conformance/canonical.json")
	if err != nil {
		t.Fatal(err)
	}
	var suite struct {
		Registry json.RawMessage   `json:"registry"`
		Vectors  []canonicalVector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &suite); err != nil {
		t.Fatal(err)
	}
	return suite.Registry, suite.Vectors
}

func TestConformanceCanonicalRegistryIsEmbedded(t *testing.T) {
	registry, _ := loadCanonicalSuite(t)
	var want, got interface{}
	if err := json.Unmarshal(registry, &want); err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(CanonicalRegistryJSON(), &got); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(want, got) {
		t.Fatal("canonical_registry.json differs from the suite: write the suite's registry member to it")
	}
}

func TestConformanceCanonicalVectors(t *testing.T) {
	_, vectors := loadCanonicalSuite(t)
	if len(vectors) < 60 {
		t.Fatalf("only %d vectors", len(vectors))
	}
	for _, v := range vectors {
		switch v.Kind {
		case "unknown_fields":
			got, err := UnknownFields(v.Model, v.Record)
			if err != nil {
				t.Fatalf("%s: %v", v.ID, err)
			}
			want := append([]string(nil), v.Expected.UnknownFields...)
			sort.Strings(want)
			if len(got) != len(want) || (len(got) > 0 && !reflect.DeepEqual(got, want)) {
				t.Errorf("%s: got %v, want %v", v.ID, got, want)
			}
		case "entry_kind":
			if IsKnownEntryKind(v.EntryKind) != *v.Expected.Known {
				t.Errorf("%s: known=%v", v.ID, !*v.Expected.Known)
			}
		default:
			t.Errorf("%s: unknown kind %s", v.ID, v.Kind)
		}
	}
}

func withField(t *testing.T, raw json.RawMessage, key string) []byte {
	t.Helper()
	obj, err := decodeObject(raw, "record")
	if err != nil {
		t.Fatal(err)
	}
	obj[key] = "x"
	out, err := json.Marshal(obj)
	if err != nil {
		t.Fatal(err)
	}
	return out
}

func TestVerifiersRefuseFieldsTheyDoNotKnow(t *testing.T) {
	vectors := loadVectors(t)
	byID := map[string]vector{}
	for _, v := range vectors {
		byID[v.ID] = v
	}

	bd := byID["bd-003"]
	now, err := ParseTimestamp(text(t, bd.Input["now"]))
	if err != nil {
		t.Fatal(err)
	}
	opts := DecisionVerifyOptions{OperatorPublicKeys: strings_(t, bd.Input["operator_public_keys"]), Now: now}
	ok, err := VerifyBoundaryDecision(bd.Input["decision"], opts)
	if err != nil || ok.Reason != "authorized" {
		t.Fatalf("baseline: %+v %v", ok, err)
	}
	later, err := VerifyBoundaryDecision(withField(t, bd.Input["decision"], "risk_tier"), opts)
	if err != nil || later.Accepted || later.Reason != "unknown_field" {
		t.Fatalf("decision with an unknown field: %+v %v", later, err)
	}
	var policies []json.RawMessage
	if err := json.Unmarshal(byID["bd-001"].Input["expected_policies"], &policies); err != nil {
		t.Fatal(err)
	}
	withPolicy := opts
	withPolicy.ExpectedPolicies = [][]byte{withField(t, policies[0], "x")}
	if got, _ := VerifyBoundaryDecision(bd.Input["decision"], withPolicy); got.Reason != "unknown_field" {
		t.Fatalf("expected policy with an unknown field: %+v", got)
	}

	agr := byID["agr-001"]
	res, err := VerifyAgreement(withField(t, agr.Input["agreement"], "x"),
		strings_(t, agr.Input["offerer_public_keys"]), strings_(t, agr.Input["responder_public_keys"]), "")
	if err != nil || res.Reason != "unknown_field" {
		t.Fatalf("agreement with an unknown field: %+v %v", res, err)
	}

	pol := byID["pol-001"]
	valid, err := VerifyDataLicensePolicySignature(withField(t, pol.Input["policy"], "x"), strings_(t, pol.Input["licensor_public_keys"]))
	if err != nil || valid {
		t.Fatalf("policy with an unknown field verified: %v %v", valid, err)
	}

	in := byID["int-001"]
	at, _ := ParseTimestamp(text(t, in.Input["at"]))
	intent, err := VerifyDataAccessIntent(withField(t, in.Input["intent"], "x"), in.Input["policy"],
		strings_(t, in.Input["agent_public_keys"]), at)
	if err != nil || intent.Valid || intent.ViolationReason != "intent_exceeds_license" {
		t.Fatalf("intent with an unknown field: %+v %v", intent, err)
	}
}
