package genesismesh

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// The conformance vectors are generated by the Python reference
// (genesismesh/conformance/generate_vectors.py interop) and copied here
// unchanged. Every vector must produce exactly the reference outcome.

type vector struct {
	ID          string                     `json:"id"`
	Kind        string                     `json:"kind"`
	Description string                     `json:"description"`
	Input       map[string]json.RawMessage `json:"input"`
	Expected    map[string]interface{}     `json:"expected"`
}

func loadVectors(t *testing.T) []vector {
	t.Helper()
	raw, err := os.ReadFile("testdata/conformance/interop.json")
	if err != nil {
		t.Fatal(err)
	}
	var suite struct {
		Suite   string   `json:"suite"`
		Vectors []vector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &suite); err != nil {
		t.Fatal(err)
	}
	if suite.Suite != "interop" || len(suite.Vectors) == 0 {
		t.Fatalf("unexpected suite %q with %d vectors", suite.Suite, len(suite.Vectors))
	}
	return suite.Vectors
}

func strings_(t *testing.T, raw json.RawMessage) []string {
	t.Helper()
	var out []string
	if len(raw) == 0 {
		return out
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatal(err)
	}
	return out
}

func text(t *testing.T, raw json.RawMessage) string {
	t.Helper()
	var s string
	if err := json.Unmarshal(raw, &s); err != nil {
		t.Fatal(err)
	}
	return s
}

func TestConformanceInteropVectors(t *testing.T) {
	kinds := map[string]int{}
	for _, v := range loadVectors(t) {
		v := v
		kinds[v.Kind]++
		t.Run(v.ID, func(t *testing.T) {
			var got map[string]interface{}
			switch v.Kind {
			case "canonical_json":
				c, err := CanonicalJSON([]byte(text(t, v.Input["json"])))
				if err != nil {
					t.Fatal(err)
				}
				got = map[string]interface{}{"canonical": c}
			case "agreement":
				digest := ""
				if raw, ok := v.Input["expected_graph_digest"]; ok {
					digest = text(t, raw)
				}
				res, err := VerifyAgreement(v.Input["agreement"], strings_(t, v.Input["offerer_public_keys"]),
					strings_(t, v.Input["responder_public_keys"]), digest)
				if err != nil {
					t.Fatal(err)
				}
				got = map[string]interface{}{"accepted": res.Accepted, "reason": res.Reason}
			case "boundary_decision":
				now, err := ParseTimestamp(text(t, v.Input["now"]))
				if err != nil {
					t.Fatal(err)
				}
				opts := DecisionVerifyOptions{OperatorPublicKeys: strings_(t, v.Input["operator_public_keys"]), Now: now}
				if raw, ok := v.Input["expected_policies"]; ok {
					var list []json.RawMessage
					if err := json.Unmarshal(raw, &list); err != nil {
						t.Fatal(err)
					}
					opts.ExpectedPolicies = [][]byte{}
					for _, p := range list {
						opts.ExpectedPolicies = append(opts.ExpectedPolicies, p)
					}
				}
				if raw, ok := v.Input["expected_attestation"]; ok {
					opts.ExpectedAttestation = raw
				}
				res, err := VerifyBoundaryDecision(v.Input["decision"], opts)
				if err != nil {
					t.Fatal(err)
				}
				got = map[string]interface{}{"accepted": res.Accepted, "reason": res.Reason, "authorized": res.Authorized}
			case "data_license_policy":
				ok, err := VerifyDataLicensePolicySignature(v.Input["policy"], strings_(t, v.Input["licensor_public_keys"]))
				if err != nil {
					t.Fatal(err)
				}
				got = map[string]interface{}{"valid": ok}
			case "data_access_intent":
				at, err := ParseTimestamp(text(t, v.Input["at"]))
				if err != nil {
					t.Fatal(err)
				}
				res, err := VerifyDataAccessIntent(v.Input["intent"], v.Input["policy"], strings_(t, v.Input["agent_public_keys"]), at)
				if err != nil {
					t.Fatal(err)
				}
				types := []interface{}{}
				for _, vio := range res.Violations {
					types = append(types, vio.ViolationType)
				}
				var reason interface{}
				if res.ViolationReason != "" {
					reason = res.ViolationReason
				}
				got = map[string]interface{}{"valid": res.Valid, "violation_reason": reason, "violation_types": types}
			default:
				t.Fatalf("unknown vector kind %q", v.Kind)
			}
			if !reflect.DeepEqual(got, v.Expected) {
				t.Fatalf("%s\n got:  %#v\n want: %#v", v.Description, got, v.Expected)
			}
		})
	}
	for _, kind := range []string{"canonical_json", "agreement", "boundary_decision", "data_license_policy", "data_access_intent"} {
		if kinds[kind] == 0 {
			t.Errorf("no %s vectors", kind)
		}
	}
}

func TestCanonicalJSONMatchesPythonForGoValues(t *testing.T) {
	// Values built in Go (admin request bodies) encode as Python re-encodes them.
	got, err := marshalCanonical(map[string]interface{}{
		"é": "Zürich ✓ 😀", "f": 0.25, "big": 1e21, "small": 0.00001, "n": 42, "del": "\u007f",
	})
	if err != nil {
		t.Fatal(err)
	}
	want := `{"big":1e+21,"del":"\u007f","f":0.25,"n":42,"small":1e-05,"\u00e9":"Z\u00fcrich \u2713 \ud83d\ude00"}`
	if string(got) != want {
		t.Fatalf("got  %s\nwant %s", got, want)
	}
}

func TestTamperedPolicyBindingIsRejected(t *testing.T) {
	for _, v := range loadVectors(t) {
		if v.ID != "bd-001" {
			continue
		}
		var d map[string]interface{}
		_ = json.Unmarshal(v.Input["decision"], &d)
		d["policy_binding"].(map[string]interface{})["policy_set_digest"] = "00"
		raw, _ := json.Marshal(d)
		now, _ := ParseTimestamp(text(t, v.Input["now"]))
		res, err := VerifyBoundaryDecision(raw, DecisionVerifyOptions{OperatorPublicKeys: strings_(t, v.Input["operator_public_keys"]), Now: now})
		if err != nil {
			t.Fatal(err)
		}
		if res.Accepted || res.Reason != "invalid_signature" {
			t.Fatalf("tampered binding accepted: %+v", res)
		}
		return
	}
	t.Fatal("bd-001 not found")
}

func interopVector(t *testing.T, id string) vector {
	t.Helper()
	for _, v := range loadVectors(t) {
		if v.ID == id {
			return v
		}
	}
	t.Fatalf("no vector %s", id)
	return vector{}
}

// conformanceKey returns the vector generator's signing key (seeds 00..1f,
// 20..3f, 40..5f) for one of pubs.
func conformanceKey(t *testing.T, pubs []string) ed25519.PrivateKey {
	t.Helper()
	for start := 0; start < 96; start += 32 {
		seed := make([]byte, ed25519.SeedSize)
		for i := range seed {
			seed[i] = byte(start + i)
		}
		key := ed25519.NewKeyFromSeed(seed)
		pub := base64.StdEncoding.EncodeToString(key.Public().(ed25519.PublicKey))
		for _, p := range pubs {
			if p == pub {
				return key
			}
		}
	}
	t.Fatal("no generator key for these public keys")
	return nil
}

// resigned signs record over its signed form, as the vector generator does.
func resigned(t *testing.T, record object, key ed25519.PrivateKey, omitWhenNull ...string) []byte {
	t.Helper()
	c, err := canonicalOf(without(record, []string{"signature"}, omitWhenNull...))
	if err != nil {
		t.Fatal(err)
	}
	record["signature"] = map[string]interface{}{
		"key_id": "k", "sig": base64.StdEncoding.EncodeToString(ed25519.Sign(key, []byte(c))),
	}
	raw, err := json.Marshal(record)
	if err != nil {
		t.Fatal(err)
	}
	return raw
}

func withValue(t *testing.T, raw json.RawMessage, key string, value interface{}) object {
	t.Helper()
	obj, err := decodeObject(raw, "record")
	if err != nil {
		t.Fatal(err)
	}
	obj[key] = value
	return obj
}

func TestASignatureIsMissingOnlyWhenAbsentOrNull(t *testing.T) {
	// v1.3.1: as in the reference; a signature of another shape fails as
	// invalid_signature ({"sig": ""} was missing_signature here).
	bd := interopVector(t, "bd-003")
	now, _ := ParseTimestamp(text(t, bd.Input["now"]))
	opts := DecisionVerifyOptions{OperatorPublicKeys: strings_(t, bd.Input["operator_public_keys"]), Now: now}
	verify := func(record object) DecisionVerification {
		t.Helper()
		raw, _ := json.Marshal(record)
		got, err := VerifyBoundaryDecision(raw, opts)
		if err != nil {
			t.Fatal(err)
		}
		return got
	}
	for _, sig := range []interface{}{
		map[string]interface{}{"key_id": "k", "sig": ""}, map[string]interface{}{}, "abc", []interface{}{}, 5,
	} {
		if got := verify(withValue(t, bd.Input["decision"], "signature", sig)); got.Reason != "invalid_signature" {
			t.Errorf("signature %v: %+v", sig, got)
		}
	}
	if got := verify(withValue(t, bd.Input["decision"], "signature", nil)); got.Reason != "missing_signature" {
		t.Errorf("null signature: %+v", got)
	}
	absent := withValue(t, bd.Input["decision"], "signature", nil)
	delete(absent, "signature")
	if got := verify(absent); got.Reason != "missing_signature" {
		t.Errorf("no signature: %+v", got)
	}
	expired := interopVector(t, "bd-006")
	expiredAt, _ := ParseTimestamp(text(t, expired.Input["now"]))
	raw, _ := json.Marshal(withValue(t, expired.Input["decision"], "signature", map[string]interface{}{"sig": ""}))
	got, err := VerifyBoundaryDecision(raw, DecisionVerifyOptions{
		OperatorPublicKeys: strings_(t, expired.Input["operator_public_keys"]), Now: expiredAt,
	})
	if err != nil || got.Reason != "decision_expired" {
		t.Errorf("expired, empty signature: %+v %v", got, err)
	}

	in := interopVector(t, "int-001")
	at, _ := ParseTimestamp(text(t, in.Input["at"]))
	for sig, want := range map[string]string{
		`{"key_id":"k","sig":""}`: "Invalid intent signature", `"abc"`: "Invalid intent signature",
		"null": "Missing intent signature",
	} {
		var value interface{}
		_ = json.Unmarshal([]byte(sig), &value)
		raw, _ := json.Marshal(withValue(t, in.Input["intent"], "signature", value))
		got, err := VerifyDataAccessIntent(raw, in.Input["policy"], strings_(t, in.Input["agent_public_keys"]), at)
		if err != nil || got.Valid || got.Violations[0].Detail != want {
			t.Errorf("intent signature %s: %+v %v", sig, got, err)
		}
	}
}

func TestAnExpiryThatDoesNotParseIsLeftToTheSignatureAndFormChecks(t *testing.T) {
	// v1.3.1: as in the reference; it was an error before any of them.
	newer := registryVector(t, "verify-decision-newer-signed-field").Input
	now, _ := ParseTimestamp(text(t, newer["now"]))
	keys := strings_(t, newer["operator_public_keys"])
	opts := DecisionVerifyOptions{OperatorPublicKeys: keys, Now: now}
	key := conformanceKey(t, keys)
	for _, value := range []interface{}{"x", "", nil, true} {
		raw := resigned(t, withValue(t, newer["decision"], "decision_valid_until", value), key, decisionOmittedWhenAbsent...)
		if got, err := VerifyBoundaryDecision(raw, opts); err != nil || got.Reason != "unknown_field" {
			t.Errorf("decision_valid_until %v: %+v %v", value, got, err)
		}
	}
	unsigned, _ := json.Marshal(withValue(t, newer["decision"], "decision_valid_until", "x"))
	if got, err := VerifyBoundaryDecision(unsigned, opts); err != nil || got.Reason != "invalid_signature" {
		t.Errorf("not re-signed: %+v %v", got, err)
	}
	// Nothing else refuses it: the expiry's error, never an acceptance.
	bd := interopVector(t, "bd-003")
	raw := resigned(t, withValue(t, bd.Input["decision"], "decision_valid_until", 5), key, decisionOmittedWhenAbsent...)
	if got, err := VerifyBoundaryDecision(raw, DecisionVerifyOptions{OperatorPublicKeys: keys, Now: now}); err == nil {
		t.Errorf("an expiry of 5 verified: %+v", got)
	}
}
