package genesismesh

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// The conformance vectors are generated by the Python reference
// (genesismesh/conformance/generate_vectors.py interop) and copied here
// unchanged. Every vector must produce exactly the reference outcome.

type vector struct {
	ID          string                     `json:"id"`
	Kind        string                     `json:"kind"`
	Description string                     `json:"description"`
	Input       map[string]json.RawMessage `json:"input"`
	Expected    map[string]interface{}     `json:"expected"`
}

func loadVectors(t *testing.T) []vector {
	t.Helper()
	raw, err := os.ReadFile("testdata/conformance/interop.json")
	if err != nil {
		t.Fatal(err)
	}
	var suite struct {
		Suite   string   `json:"suite"`
		Vectors []vector `json:"vectors"`
	}
	if err := json.Unmarshal(raw, &suite); err != nil {
		t.Fatal(err)
	}
	if suite.Suite != "interop" || len(suite.Vectors) == 0 {
		t.Fatalf("unexpected suite %q with %d vectors", suite.Suite, len(suite.Vectors))
	}
	return suite.Vectors
}

func strings_(t *testing.T, raw json.RawMessage) []string {
	t.Helper()
	var out []string
	if len(raw) == 0 {
		return out
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		t.Fatal(err)
	}
	return out
}

func text(t *testing.T, raw json.RawMessage) string {
	t.Helper()
	var s string
	if err := json.Unmarshal(raw, &s); err != nil {
		t.Fatal(err)
	}
	return s
}

func TestConformanceInteropVectors(t *testing.T) {
	kinds := map[string]int{}
	for _, v := range loadVectors(t) {
		v := v
		kinds[v.Kind]++
		t.Run(v.ID, func(t *testing.T) {
			var got map[string]interface{}
			switch v.Kind {
			case "canonical_json":
				c, err := CanonicalJSON([]byte(text(t, v.Input["json"])))
				if err != nil {
					t.Fatal(err)
				}
				got = map[string]interface{}{"canonical": c}
			case "agreement":
				digest := ""
				if raw, ok := v.Input["expected_graph_digest"]; ok {
					digest = text(t, raw)
				}
				res, err := VerifyAgreement(v.Input["agreement"], strings_(t, v.Input["offerer_public_keys"]),
					strings_(t, v.Input["responder_public_keys"]), digest)
				if err != nil {
					t.Fatal(err)
				}
				got = map[string]interface{}{"accepted": res.Accepted, "reason": res.Reason}
			case "boundary_decision":
				now, err := ParseTimestamp(text(t, v.Input["now"]))
				if err != nil {
					t.Fatal(err)
				}
				opts := DecisionVerifyOptions{OperatorPublicKeys: strings_(t, v.Input["operator_public_keys"]), Now: now}
				if raw, ok := v.Input["expected_policies"]; ok {
					var list []json.RawMessage
					if err := json.Unmarshal(raw, &list); err != nil {
						t.Fatal(err)
					}
					opts.ExpectedPolicies = [][]byte{}
					for _, p := range list {
						opts.ExpectedPolicies = append(opts.ExpectedPolicies, p)
					}
				}
				if raw, ok := v.Input["expected_attestation"]; ok {
					opts.ExpectedAttestation = raw
				}
				res, err := VerifyBoundaryDecision(v.Input["decision"], opts)
				if err != nil {
					t.Fatal(err)
				}
				got = map[string]interface{}{"accepted": res.Accepted, "reason": res.Reason, "authorized": res.Authorized}
			case "data_license_policy":
				ok, err := VerifyDataLicensePolicySignature(v.Input["policy"], strings_(t, v.Input["licensor_public_keys"]))
				if err != nil {
					t.Fatal(err)
				}
				got = map[string]interface{}{"valid": ok}
			case "data_access_intent":
				at, err := ParseTimestamp(text(t, v.Input["at"]))
				if err != nil {
					t.Fatal(err)
				}
				res, err := VerifyDataAccessIntent(v.Input["intent"], v.Input["policy"], strings_(t, v.Input["agent_public_keys"]), at)
				if err != nil {
					t.Fatal(err)
				}
				types := []interface{}{}
				for _, vio := range res.Violations {
					types = append(types, vio.ViolationType)
				}
				var reason interface{}
				if res.ViolationReason != "" {
					reason = res.ViolationReason
				}
				got = map[string]interface{}{"valid": res.Valid, "violation_reason": reason, "violation_types": types}
			default:
				t.Fatalf("unknown vector kind %q", v.Kind)
			}
			if !reflect.DeepEqual(got, v.Expected) {
				t.Fatalf("%s\n got:  %#v\n want: %#v", v.Description, got, v.Expected)
			}
		})
	}
	for _, kind := range []string{"canonical_json", "agreement", "boundary_decision", "data_license_policy", "data_access_intent"} {
		if kinds[kind] == 0 {
			t.Errorf("no %s vectors", kind)
		}
	}
}

func TestCanonicalJSONMatchesPythonForGoValues(t *testing.T) {
	// Values built in Go (admin request bodies) encode as Python re-encodes them.
	got, err := marshalCanonical(map[string]interface{}{
		"é": "Zürich ✓ 😀", "f": 0.25, "big": 1e21, "small": 0.00001, "n": 42, "del": "\u007f",
	})
	if err != nil {
		t.Fatal(err)
	}
	want := `{"big":1e+21,"del":"\u007f","f":0.25,"n":42,"small":1e-05,"\u00e9":"Z\u00fcrich \u2713 \ud83d\ude00"}`
	if string(got) != want {
		t.Fatalf("got  %s\nwant %s", got, want)
	}
}

func TestTamperedPolicyBindingIsRejected(t *testing.T) {
	for _, v := range loadVectors(t) {
		if v.ID != "bd-001" {
			continue
		}
		var d map[string]interface{}
		_ = json.Unmarshal(v.Input["decision"], &d)
		d["policy_binding"].(map[string]interface{})["policy_set_digest"] = "00"
		raw, _ := json.Marshal(d)
		now, _ := ParseTimestamp(text(t, v.Input["now"]))
		res, err := VerifyBoundaryDecision(raw, DecisionVerifyOptions{OperatorPublicKeys: strings_(t, v.Input["operator_public_keys"]), Now: now})
		if err != nil {
			t.Fatal(err)
		}
		if res.Accepted || res.Reason != "invalid_signature" {
			t.Fatalf("tampered binding accepted: %+v", res)
		}
		return
	}
	t.Fatal("bd-001 not found")
}
